version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: signup-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: signup_practice
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
